### ISSUE TITLE
Increment sequence number upon edition

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#12]
This issue was moved from the issue tracker at GitLab.

---

Increment the [sequence number](https://tools.ietf.org/html/rfc5545#section-3.8.7.4) every time the file is modified/save.

* [x] `SEQUENCE`
* [x] `LAST-MODIFIED`

**Comment by Sakshisaraswat** [comment]
hello everyone !! i want to solve this issue.
please help me where to start

**Comment by untitaker** [comment]
Hello @Sakshisaraswat,

For this issue we need to increment the `SEQUENCE` property of `self.todo` [right here](https://github.com/pimutils/todoman/blob/master/todoman/model.py#L326). `self.todo` is something like a dictionary, so you would have to get the value for the key `"sequence"` (or use 0 if it doesn't exist) and save it back increased by `1`.

Also there's a property called `LAST-MODIFIED` that we should probably update too. It needs to be set to the current datetime (`datetime.now()`). However, instead of calling `now()` directly, I would do `self.now = datetime.now()` in `FileTodo.__init__`. This is useful because then we can replace `self.now` with a fixed value for testing purposes.

**Comment by Sakshisaraswat** [comment]
What should be the strategy to save the variable so that it does not reset at end of session?

**Comment by untitaker** [comment]
You shouldn't have to do anything special. Do you have code that does reset?

**Comment by hobarrera** [comment]
@Sakshisaraswat `todo`s are saved to disk, so any values we assign it (including `SEQUENCE` and `LAST-MODIFIED` are retained.
