### ISSUE TITLE
Granular priority support

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#132]
The icalendar format [supports priority [1-9]](https://tools.ietf.org/html/rfc5545#section-3.8.1.9), but we only support no priority, or 1 (but nothing from 2 to 9). (Note: 1 is the highest priority, 9 is the lowest).

It might be cool to see some support for this, but we also need to discuss some stuff:

* Do we show a `!` for priority > 9 when listing?
  * As an alternative, do we want to show `!`, `!!` and `!!!` for different ranges?
* Does priority affect ordering? (I think it should).
* Do we have any sort of "slider" for the interactive UI?
* How does this affect filtering?

I'm opening this to open up discussion and interest in this.

**Comment by untitaker** [comment]
From the RFC:

      A CUA with a three-level priority scheme of "HIGH", "MEDIUM", and
      "LOW" is mapped into this property such that a property value in
      the range of 1 to 4 specifies "HIGH" priority.  A value of 5 is
      the normal or "MEDIUM" priority.  A value in the range of 6 to 9
      is "LOW" priority.

These three levels should be easier to represent: `"   "` for no priority, `"  !"` for LOW, `" !!"` for MEDIUM, `"!!!"` for HIGH.

**Comment by untitaker** [comment]
That schema is also what the OpenTasks app for Android uses.

**Comment by hobarrera** [comment]
Perfect! I had something similar in mind (I'd though 1-3 as high). But if it's standardised, even better!

**Comment by hobarrera** [comment]
#130 makes this a lot less painful to implement too.

And I think it might actually be an easy/medium task (it's just long, not hard).

**Comment by mansimarkaur** [comment]
So, users will have to specify a number in the specific range to create a task with the required priority and when they want a list to be displayed with the specific priority, strings like high, medium will be used (#19 )?

**Comment by untitaker** [comment]
Ah no, I think whatever we do, the strings for entering and displaying should
be the same.

Also I think at no point we should expose specific priority ranges (1-9) in the
todoman UI.

**Comment by mansimarkaur** [comment]
Also, do we want specifying the priority to be mandatory?
If not, do we default it to low?
I'm working on #19 and I feel this issue needs to be resolved before filtering by priority can be done?
What are your views on this?

**Comment by untitaker** [comment]
That's a good question. I think there needs to be a new value called `"none"`, which is the default and translates to `0`.

At least in OpenTasks there's a dropdown with the entries "none", "low", "medium", "high".

Also you're right, #19 and #132 are closely related. I think it would be a good idea to translate those four values in `TodoFormatter` to integers and back. So we would have a method called `parse_priority` which takes a string and returns:

* integer `9` if the string is "low".
* integer `5` if the string is "medium".
* integer `4` if the string is "high".
* integer `0` if "none".

Then `Database.todos` needs a `priority` parameter (instead of `urgent`). If the parameter is not `0`, we add a `WHERE` clause that returns only the tasks where the `priority` field is `<=` the given value.

To be clear @mansimarkaur, do you want to work on this part too? I can do that if you want to purely focus on #19.

**Comment by mansimarkaur** [comment]
Yes, I'd love to work on this part as well.

**Comment by untitaker** [comment]
Fantastic, let's focus on #136 for now and delay displaying priorities to a different PR

**Comment by hobarrera** [comment]
> Fantastic, let's focus on #136 for now and delay displaying priorities to a different PR

Indeed, there's a few different very-related features for this issue that can be separate PRs, to keep them simple. ^_^

**Comment by mansimarkaur** [comment]
Do we want to show ! for high or !!! for high?

**Comment by mansimarkaur** [comment]
What additions are required to fix this issue now that #136 is merged?

**Comment by untitaker** [comment]
Nothing I think? You just sort of got pulled into doing everything at once :+1:
