### ISSUE TITLE
vulture reports dead code

### ISSUE THREAD

**Issue by RJ722** [pimutils/todoman#253]
We used vulture (https://github.com/jendrikseipp/vulture) to search for unused code in your project. You can find the report below. It would be great if you could give us feedback about which items are actually used or unused. This would allow us to improve vulture and ideally it also helps you to remove obsolete code or even find typos and bugs.
Command:
    
    vulture todoman --exclude todoman/.tox/

Raw result:
```
todoman/docs/source/conf.py:105: Unused variable 'extensions'
todoman/docs/source/conf.py:113: Unused variable 'templates_path'
todoman/docs/source/conf.py:118: Unused variable 'source_suffix'
todoman/docs/source/conf.py:127: Unused variable 'project'
todoman/docs/source/conf.py:128: Unused variable 'copyright'
todoman/docs/source/conf.py:138: Unused variable 'release'
todoman/docs/source/conf.py:145: Unused variable 'language'
todoman/docs/source/conf.py:155: Unused variable 'exclude_patterns'
todoman/docs/source/conf.py:173: Unused variable 'pygments_style'
todoman/docs/source/conf.py:182: Unused variable 'todo_include_todos'
todoman/docs/source/conf.py:189: Unused variable 'html_theme'
todoman/docs/source/conf.py:194: Unused variable 'html_theme_options'
todoman/docs/source/conf.py:224: Unused variable 'html_static_path'
todoman/docs/source/conf.py:240: Unused variable 'html_sidebars'
todoman/docs/source/conf.py:295: Unused variable 'htmlhelp_basename'
todoman/docs/source/conf.py:299: Unused variable 'latex_elements'
todoman/docs/source/conf.py:316: Unused variable 'latex_documents'
todoman/docs/source/conf.py:346: Unused variable 'man_pages'
todoman/docs/source/conf.py:360: Unused variable 'texinfo_documents'
todoman/tests/test_model.py:213: Unused variable 'until'
todoman/tests/test_ui.py:142: Unused attribute 'state'
todoman/todoman/cli.py:39: Unused variable 'param'
todoman/todoman/cli.py:343: Unused function 'show'
todoman/todoman/cli.py:355: Unused function 'done'
todoman/todoman/interactive.py:122: Unused variable 'radio_button'
todoman/todoman/interactive.py:154: Unused variable 'btn'
todoman/todoman/model.py:25: Unused class 'UnsafeOperationException'
todoman/todoman/model.py:55: Unused variable 'cls'
todoman/todoman/model.py:407: Unused attribute 'row_factory'
```
Obvious false-positives:
```
todoman/docs/source/conf.py:105: Unused variable 'extensions'
todoman/docs/source/conf.py:113: Unused variable 'templates_path'
todoman/docs/source/conf.py:118: Unused variable 'source_suffix'
todoman/docs/source/conf.py:127: Unused variable 'project'
todoman/docs/source/conf.py:128: Unused variable 'copyright'
todoman/docs/source/conf.py:138: Unused variable 'release'
todoman/docs/source/conf.py:145: Unused variable 'language'
todoman/docs/source/conf.py:155: Unused variable 'exclude_patterns'
todoman/docs/source/conf.py:173: Unused variable 'pygments_style'
todoman/docs/source/conf.py:182: Unused variable 'todo_include_todos'
todoman/docs/source/conf.py:189: Unused variable 'html_theme'
todoman/docs/source/conf.py:194: Unused variable 'html_theme_options'
todoman/docs/source/conf.py:224: Unused variable 'html_static_path'
todoman/docs/source/conf.py:240: Unused variable 'html_sidebars'
todoman/docs/source/conf.py:295: Unused variable 'htmlhelp_basename'
todoman/docs/source/conf.py:299: Unused variable 'latex_elements'
todoman/docs/source/conf.py:316: Unused variable 'latex_documents'
todoman/docs/source/conf.py:346: Unused variable 'man_pages'
todoman/docs/source/conf.py:360: Unused variable 'texinfo_documents'
```    
Unused code or false-positives:
```
todoman/tests/test_model.py:213: Unused variable 'until'
todoman/tests/test_ui.py:142: Unused attribute 'state'
todoman/todoman/cli.py:39: Unused variable 'param'
todoman/todoman/cli.py:343: Unused function 'show'
todoman/todoman/cli.py:355: Unused function 'done'
todoman/todoman/interactive.py:122: Unused variable 'radio_button'
todoman/todoman/interactive.py:154: Unused variable 'btn'
todoman/todoman/model.py:25: Unused class 'UnsafeOperationException'
todoman/todoman/model.py:55: Unused variable 'cls'
todoman/todoman/model.py:407: Unused attribute 'row_factory'
```
There might be false positives, which can be prevented by adding them to a
whitelist file. You may find more info [here](https://github.com/jendrikseipp/vulture#usage)

Regards,
vulture team

**Comment by hobarrera** [comment]
Huh, nice find. A few of these actually expose more interesting errors, like variables in tests that **should** be used, but since they're not, the test is less complete. I'll start addressing them.

**Comment by hobarrera** [comment]
I noticed that you're contributing with upstream a bit, so here are some hints in case you want to work around these false positives (it should be possible to infer their usage somehow, since a reference IS kept elsewhere):

* Regarding the ones in `docs`: you probably just want to run it in the main package directory (and `tests`)
* `tests/test_ui.py:142: Unused attribute 'state'`: This variable is actually used internally by urwid. Maybe it's in C code?
* `todoman/cli.py:39: Unused variable 'param'`: This function is passed as a parameter elsewhere, so it needs to receive the expected arguments. Maybe unused params could be ignored in case of functions that are passed as arguments elsewhere?
* `todoman/interactive.py:122: Unused variable 'radio_button'` Ditto
* `todoman/interactive.py:154: Unused variable 'btn'` Same
* `todoman/cli.py:343: Unused function 'show'`: The decorator here registers the function itself, but I'm not sure if an AST fill reveal this, so I'm not sure if it's possible to check for this.
* `todoman/cli.py:355: Unused function 'done'`: Ditto.
* `todoman/model.py:45: Unused variable 'cls'`: `__get__` has pre-defined parameters, so we MUST accept those same ones.
* `todoman/model.py:397: Unused attribute 'row_factory'`: This attribute is actually used -- again, it's possibel that it's C code, but removing this line results in huge failures.
