### ISSUE TITLE
install error from AUR

### ISSUE THREAD

**Issue by aleprovencio** [pimutils/todoman#302]
Hello, I'm getting an `ImportError` for `tests.helpers` while trying to install todoman from AUR with trizen.
Please let me know if I should post this on the package's AUR page.

Relevant output:
```
_____________________________ ERROR collecting tests/test_cli.py ______________________________
ImportError while importing test module '/tmp/trizen-aleprovencio/todoman/src/todoman-3.2.4/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_cli.py:14: in <module>
    from tests.helpers import pyicu_sensitive
E   ModuleNotFoundError: No module named 'tests.helpers'
__________________________ ERROR collecting tests/test_formatter.py ___________________________
ImportError while importing test module '/tmp/trizen-aleprovencio/todoman/src/todoman-3.2.4/tests/test_formatter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_formatter.py:7: in <module>
    from tests.helpers import pyicu_sensitive
E   ModuleNotFoundError: No module named 'tests.helpers'
```

**Comment by doronbehar** [comment]
That also happens when running just `py.test` from the release of version `3.3.0`.

**Comment by WhyNotHugo** [comment]
@doronbehar `v3.3.0` fails some tests due to some upstream changes.
I've pushed v3.4.0, which includes these fixes. I'll update AUR soon.

@aleprovencio Is this still an issue for you?

**Comment by doronbehar** [comment]
I still experience the same issue with the latest git version which is identical at the moment to `v3.4.0`.

**Comment by aleprovencio** [comment]
same here :/

**Comment by doronbehar** [comment]
Confirmed.

**Comment by WhyNotHugo** [comment]
Can you add this into the `check()` function in the `PKGBUILD`, and tell me what the output is? I'm kind of at a loss:

```
python -c "import tests; print(tests.__path__)"
```

**Comment by aleprovencio** [comment]
output;
```['/home/aleprovencio/.local/lib/python3.6/site-packages/tests']```

**Comment by doronbehar** [comment]
@WhyNotHugo, I don't think it is a matter related to the way the AUR package is built. I get the same errors when I clone your repository fresh and I run `py.test` from it's root directory.

When I run the command you specified in your [last comment](https://github.com/pimutils/todoman/issues/302#issuecomment-390312800), I got the following output:
```
['/usr/lib/python3.6/site-packages/tests']
```
Since I'm using Arch Linux, running `pacman -Qoq /usr/lib/python3.6.site-packages/tests` (I ask `pacman` to tell me what packages own this file / directory) Gives me:
```
python-gogs-client
python-pipenv
```
I believe that means the `import tests` statement is importing the wrong modules. I guess that if we'd remove these specific packages, the tests should pass just fine. But of course that's not a solution but a workaround. I think `todoman` should change the name of the `tests/` directory perhaps to something like `todoman_tests` and update the rest of the tests' files accordingly.

**Comment by WhyNotHugo** [comment]
What I find odd is that that `tests` is a namespace package for me; as expected:

```                                                                                                               
$ python -c "import tests; print(tests.__path__)"
_NamespacePath(['/usr/lib/python3.6/site-packages/tests'])
$ pacman -Qo /usr/lib/python3.6/site-packages/tests
/usr/lib/python3.6/site-packages/tests/ is owned by python-pipenv 2018.05.18-1
```
> I believe that means the import tests statement is importing the wrong modules. I guess that if we'd remove these specific packages, the tests should pass just fine. But of course that's not a solution but a workaround. I think todoman should change the name of the tests/ directory perhaps to something like todoman_tests and update the rest of the tests' files accordingly.

Nope, using `tests` as a package name is super common (I'd say _most_ package with tests do that). The issue lies elsewhere. I'm confused why your python doesn't 

---

Actually, I debugged this a bit. `python-gogs-client` includes `/usr/lib/python3.6/site-packages/tests/__init__.py`. This breaks `tests` as a [namespace package](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages). This will basically break any tests for any python app.

I've just reported this: https://aur.archlinux.org/packages/python-gogs-client/#comment-647241

There's not much else that can be done on our end.

@aleprovencio: I suggest you find out how `/home/aleprovencio/.local/lib/python3.6/site-packages/tests/__init__.py` ended up getting created, and report that upstream too (or you can delete that file).

As a workaround, you can delete the `check()` function from the `PKGBUILD` to skip the tests entirely.
