### ISSUE TITLE
web site: output of `--help` broken

### ISSUE THREAD

**Issue by tbm** [pimutils/todoman#393]
The example output of `todo --help` in the [usage section](https://todoman.readthedocs.io/en/stable/usage.html) is broken:

```
$ todo --help
Traceback (most recent call last):
...
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by WhyNotHugo** [comment]
Your locale needs to UTF-8.

This is something we inherit from Python and there's nothing we can do about it.

I'll leave this open since there have been many similar reports and this needs to be documented.

**Comment by tbm** [comment]
No, I'm talking about the website.  The output on the readthedocs web site is broken:

https://todoman.readthedocs.io/en/stable/usage.html

**Comment by tbm** [comment]
So you whatever is building the docs for readthedocs.io needs UTF-8.

**Comment by WhyNotHugo** [comment]
Oh. When did that break?

Thanks for pointing it out, I'll have a look at it.

**Comment by tbm** [comment]
> Oh. When did that break?

I'm not sure but at least several weeks ago (but I didn't get around to filing a bug until now).

**Comment by divbzero** [comment]
As of today it’s still broken on the [Usage](https://todoman.readthedocs.io/en/stable/usage.html) page.

**Comment by WhyNotHugo** [comment]
This is broken since RTD changed _something_ in their environment locale settings, but there's nothing documented around it, so it'd be a pain to debug their build environment and figure out what's wrong.

On a clean, sane, environment, this builds fine.

#415 "fixes" the issue, since it shuffles around documentation and removes the ofending script entirely.
