### ISSUE TITLE
how do I create a new recurring task

### ISSUE THREAD

**Issue by agaAdams** [pimutils/todoman#423]
Hi everybody,

how do I create a new recurring task with todoman. I understand that I cannot edit the recurrence of an item with the edit dialogue. But how do I create a new item via command line with an recurrence?

Sorry if this has been answered in the docs, but I somehow can't figure this out.

Cheers

aga

**Comment by WhyNotHugo** [comment]
Creating recurring events is also not supported (although completing one will automatically create the next one in the series).

I usually create recurring events on my phone, and keep in sync via vdirsyncer. Another option is to manually copy the `RRULE` into the file, but that's really a big hack and prone to breakage.

Gonna leave this open, since this needs to be implemented at some point.

**Comment by agaAdams** [comment]
Ah, many thanks then for the clarification. The workaround via phone works obviously.

**Comment by WhyNotHugo** [comment]
This is a duplicate of #305
